---
sudo: required
dist: trusty

language: python
python: "2.7"

services:
- docker

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq python-apt python3-apt python-pip python3-pip sssd docker.io

install:
- pip install ansible docker-py

script:
- ansible-playbook setup.yml --extra-vars "builddir=${TRAVIS_BUILD_DIR}/"
- /test/test-all.sh
