---
sudo: required
dist: bionic
addons:
  apt:
    sources:
    - docker-bionic
    packages:
    - docker

language: python
python: "3.6"

install:
- sudo apt-get install -qq sssd
- pip install ansible docker-py
- ansible-playbook setup.yml --extra-vars "builddir=${TRAVIS_BUILD_DIR}/"

script:
- /test/test-all.sh
