---
sudo: required
dist: bionic
addons:
  apt:
    sources:
    - docker-bionic
    packages:
    - docker

language: python
python: "3.6"

install:
- pip install ansible docker-py

script:
- ansible-playbook setup.yml --extra-vars "builddir=${TRAVIS_BUILD_DIR}/"
- /test/test-all.sh
