---
- name: Build docker images
  with_items: "{{ docker.versions }}"
  docker_image:
    name: "{{ docker.basename }}:{{ item }}"
    build:
      dockerfile: "{{ builddir }}/{{ item }}/Dockerfile"
      path: "{{ builddir }}/{{ item }}/"
    source: build
    state: present
