---
- name: Build docker images
  with_items: "{{ docker.versions }}"
  docker_image:
    name: "{{ docker.basename }}:{{ item }}"
    build:
      dockerfile: "{{ builddir }}/{{ item }}/Dockerfile"
      path: "{{ builddir }}/{{ item }}/"
    source: build
    state: present


[WARNING]: The value of the "source" option was determined to be "build".
Please set the "source" option explicitly. Autodetection will be removed in
Ansible 2.12.
