---
- name: Build docker images
  with_items: "{{ docker.versions }}"
  docker_image:
    name: "{{ docker.basename }}:{{ item }}"
    dockerfile: "{{ builddir }}/{{ item }}/Dockerfile"
    path: "{{ builddir }}/{{ item }}/"
    state: build
